services:
  psql_crxdb:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=salaries_employees
    volumes:
      - "./salaries_employees_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"


  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com 
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"


  analytics:
    build:
      context: main
    environment:
      POSTGRESQL_CS: 'postgresql+psycopg2://postgres:password@psql_crxdb:5432/salaries_employees'
    depends_on:
      - psql_crxdb
    command: ["python", "./main.py" ]
    volumes:
      - "./main/input_data:/app/input" 
